// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfghXb7wmWkw_RHN6JMoUnAYFZVrshl5o',
    appId: '1:830350218175:web:cb57c030cf12d7fb9d470a',
    messagingSenderId: '830350218175',
    projectId: 'quickmed-fb84a',
    authDomain: 'quickmed-fb84a.firebaseapp.com',
    storageBucket: 'quickmed-fb84a.firebasestorage.app',
    measurementId: 'G-8Z982KKXSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqFKh1WjBW0t5ke-70DNPaJs34E5sQ2u8',
    appId: '1:830350218175:android:cc6bd46649d1ebfd9d470a',
    messagingSenderId: '830350218175',
    projectId: 'quickmed-fb84a',
    storageBucket: 'quickmed-fb84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3dJoeQZYroTEyEnws_wPcvp6e9-nAfTI',
    appId: '1:830350218175:ios:f3f2de1de5ba9d519d470a',
    messagingSenderId: '830350218175',
    projectId: 'quickmed-fb84a',
    storageBucket: 'quickmed-fb84a.firebasestorage.app',
    iosBundleId: 'com.example.quickMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3dJoeQZYroTEyEnws_wPcvp6e9-nAfTI',
    appId: '1:830350218175:ios:f3f2de1de5ba9d519d470a',
    messagingSenderId: '830350218175',
    projectId: 'quickmed-fb84a',
    storageBucket: 'quickmed-fb84a.firebasestorage.app',
    iosBundleId: 'com.example.quickMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfghXb7wmWkw_RHN6JMoUnAYFZVrshl5o',
    appId: '1:830350218175:web:8d2aa505310d35df9d470a',
    messagingSenderId: '830350218175',
    projectId: 'quickmed-fb84a',
    authDomain: 'quickmed-fb84a.firebaseapp.com',
    storageBucket: 'quickmed-fb84a.firebasestorage.app',
    measurementId: 'G-1QJLSZWW4P',
  );

}